#!/bin/sh
########################################################################
#
# This is a bit of a hack, but I feel that it is much easier and
# better to understand than forcing people to download all kind of
# fancy stuff for ant, just to run pdflatex and bibtex a few times.
#
# (C) 2007 Harald Kirsch
#
########################################################################

# Just run pdflatex often enough:-)
needRun() {
  test MonqJfaTutorial.tex -nt MonqJfaTutorial.pdf \
   || grep -qsi 'label.s. may have ch' MonqJfaTutorial.log
}

needRun || exit 0
pdflatex MonqJfaTutorial
bibtex MonqJfaTutorial

while needRun; do 
  pdflatex MonqJfaTutorial
done
